### ISSUE TITLE
Account call fails in 0.0.5 release

### ISSUE THREAD

**Issue by marbud0** [jabesq/pybotvac#5]
Trying to debug an issue with my homeassistant installation i resorted to runing the pybotvac calls isolated. And the Account call returns the following for me:

```python
(homeassistant-py3.6) homeassistant@pestus:/opt/homeassistant-py3.6$ python 
Python 3.6.4 (default, Feb 28 2018, 21:48:01) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pybotvac import Account
>>> for robot in Account('EMAIL','PASSWORD).robots:
... 	print(robot)
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homeassistant-py3.6/lib/python3.6/site-packages/pybotvac/account.py", line 61, in robots
    self.refresh_robots()
  File "/opt/homeassistant-py3.6/lib/python3.6/site-packages/pybotvac/account.py", line 105, in refresh_robots
    traits=robot['traits']))
  File "/opt/homeassistant-py3.6/lib/python3.6/site-packages/pybotvac/robot.py", line 36, in __init__
    if self.service_version not in SUPPORTED_SERVICES:
  File "/opt/homeassistant-py3.6/lib/python3.6/site-packages/pybotvac/robot.py", line 135, in service_version
    return self.available_services['houseCleaning']
  File "/opt/homeassistant-py3.6/lib/python3.6/site-packages/pybotvac/robot.py", line 131, in available_services
    return self.state['availableServices']
  File "/opt/homeassistant-py3.6/lib/python3.6/site-packages/pybotvac/robot.py", line 127, in state
    return self.get_robot_state().json()
  File "/opt/homeassistant-py3.6/lib/python3.6/site-packages/pybotvac/robot.py", line 103, in get_robot_state
    return self._message({'reqId': "1", 'cmd': "getRobotState"})
  File "/opt/homeassistant-py3.6/lib/python3.6/site-packages/pybotvac/robot.py", line 54, in _message
    headers=self._headers)
  File "/opt/homeassistant-py3.6/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/homeassistant-py3.6/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/homeassistant-py3.6/lib/python3.6/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/opt/homeassistant-py3.6/lib/python3.6/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/opt/homeassistant-py3.6/lib/python3.6/site-packages/requests/models.py", line 309, in prepare
    self.prepare_auth(auth, url)
  File "/opt/homeassistant-py3.6/lib/python3.6/site-packages/requests/models.py", line 540, in prepare_auth
    r = auth(self)
  File "/opt/homeassistant-py3.6/lib/python3.6/site-packages/pybotvac/robot.py", line 148, in __call__
    signing = hmac.new(key=self.secret.encode('utf8'),
AttributeError: 'NoneType' object has no attribute 'encode'
>>> 
```

To me it looks like the self.secret is null, but I don't get how as it's provided in the account call above.

**Comment by erikosvaldsson** [comment]
I got this error when I had non-connected botvacs (ie witout wifi) tied to my account.
When looking at the code it seems to work fine for connected bots but also tries to get secrets for non-connected bots, they obviously does not have one.

Removing non-connected bots from my account got me past this...

**Comment by rodtoll** [comment]
The only botvac I have is the Connected d7 which is Wifi connected. So
unfortunately that won’t help in this case.

It seems like they introduced a new protocol with the new device that the
client library doesn’t recognize yet. Which sounds like similar failure
type, perhaps the non WiFi models also use an unsupported protocol?

**Comment by marbud0** [comment]
I no longer have the issue as it was resolved by removing a unsused robot from my neato account. But even so still a code defect.
