### ISSUE TITLE
Botvac D7 Connected not supported

### ISSUE THREAD

**Issue by rodtoll** [jabesq/pybotvac#6]
Error initializing Robot class when the Robot is a Botvac D7 Connected. Looks like they have a new protocol version.

Error when using the library v0.0.5:
pybotvac.robot.UnsupportedDevice: Version basic-3 of service houseCleaning is not known_

Looking at v 0.0.6 it also would have the same error.

**Comment by dshokouhi** [comment]
I am also receiving this error in home assistant.

`
2018-06-15 13:57:51 ERROR (MainThread) [homeassistant.setup] Error during setup of component neato
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/setup.py", line 146, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/neato.py", line 87, in setup
    hass.data[NEATO_LOGIN] = NeatoHub(hass, config[DOMAIN], Account)
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/neato.py", line 111, in __init__
    self._hass.data[NEATO_ROBOTS] = self.my_neato.robots
  File "/srv/homeassistant/lib/python3.6/site-packages/pybotvac/account.py", line 61, in robots
    self.refresh_robots()
  File "/srv/homeassistant/lib/python3.6/site-packages/pybotvac/account.py", line 105, in refresh_robots
    traits=robot['traits']))
  File "/srv/homeassistant/lib/python3.6/site-packages/pybotvac/robot.py", line 37, in __init__
    raise UnsupportedDevice("Version " + self.service_version + " of service houseCleaning is not known")
pybotvac.robot.UnsupportedDevice: Version basic-3 of service houseCleaning is not known
`

**Comment by dshokouhi** [comment]
I think I may have found the quick fix.

I modified the following line and included 'basic-3' in the support list and it seems to be working :)

https://github.com/jabesq/pybotvac/blob/master/pybotvac/robot.py#L10

**Comment by dshokouhi** [comment]
yup can confirm the D7 is working with that small change :)

**Comment by rodtoll** [comment]
Just realized that the version on PyPI comes from a different repository. The one this one is forked from: https://github.com/stianaske/pybotvac. In that version this issue is resolved.
